# The TIA - Team!

variables:
- group: TIAKeyVault

trigger:
- '*'

schedules:
  - cron: "30 * * * *"
    displayName: Schedule job
    branches:
      include:
      - main
    always: true

#pool:
#  vmImage: $(agentImage)
pool: GreenHeartDemosAgent

jobs:
- job: LoadAgentNode1
  displayName: CBM1
  continueOnError: false
  workspace:
    clean: outputs
  steps:
    - template: ATHJob.yml
