# The TIA - Team!

trigger:
- '*'

schedules:
  - cron: "10 * * * *"
    displayName: Schedule job
    branches:
      include:
      - main
    always: true

pool:
  vmImage: $(agentImage)

jobs:
- job: LoadAgentNode1
  displayName: CBM1
  continueOnError: false
  workspace:
    clean: outputs
  steps:
    - template: ATHJob.yml
