# The TIA - Team!

steps:

- powershell: |
         $destinationFolder = "$(Build.SourcesDirectory)/ATH/aimaps/aimaps-cli/win-x64-no-driver/selenium/"
         if (!(Test-Path -path $destinationFolder)) {New-Item $destinationFolder -Type Directory}
         Copy-Item 'C:/SeleniumWebDrivers/ChromeDriver/*' $destinationFolder -Force -Recurse
  displayName: 'Install web drivers'
  
- task: PowerShell@2
  condition: eq(variables['Agent.OS'], 'Windows_NT')
  inputs:
    pws: true
    targetType: 'inline'
    script: |
      Add-VpnConnection -Name "greensqa" -ServerAddress "190.85.58.226" -TunnelType "L2tp" -L2tpPsk "greensqa" -Force -PassThru    
      $vpnname = "greensqa"
      $vpnusername = "vpn88"
      $vpnpassword = "4wt46N501VpN"
      $cmd = $env:WINDIR + "\System32\rasdial.exe"
      $connect = "$cmd ""$vpnname"" $vpnusername $vpnpassword"
      $disconnect = "$cmd ""$vpnname"" /disconnect"
      Invoke-Expression -Command $connect
      Invoke-Expression -Command $disconnect          
  displayName: 'Connect to VPN'
  timeoutInMinutes: 5
  
#- task: PowerShell@2
#  condition: eq(variables['Agent.OS'], 'Windows_NT')
#  inputs:
#    pws: true
#    targetType: 'inline'
#    script: |          
#      ./ATH/aimaps/aimaps-cli/win-x64-no-driver/Gsqa.Tools.AiMaps.Console.exe src='$(Build.SourcesDirectory)/ATH/maps/Robot_Demo_ATH.aimj'
#  displayName: 'Running robot - ATH '
#  timeoutInMinutes: 5 

- task: PowerShell@2
  condition: eq(variables['Agent.OS'], 'Windows_NT')
  inputs:
    pws: true
    targetType: 'inline'
    script: |  
      $vpnname = "greensqa"
      $cmd = $env:WINDIR + "\System32\rasdial.exe"
      $disconnect = "$cmd ""$vpnname"" /disconnect"      
      Invoke-Expression -Command $disconnect          
  displayName: 'Disconnect to VPN'
  timeoutInMinutes: 5 
