# The TIA - Team!

steps:

- powershell: |
         $destinationFolder = "$(Build.SourcesDirectory)/GyF/aimaps/aimaps-cli/win-x64/selenium/"
         if (!(Test-Path -path $destinationFolder)) {New-Item $destinationFolder -Type Directory}
         Copy-Item 'C:/SeleniumWebDrivers/ChromeDriver/*' $destinationFolder -Force -Recurse
  displayName: 'Install web drivers'
  
- task: PowerShell@2
  condition: eq(variables['Agent.OS'], 'Windows_NT')
  inputs:
    pws: true
    targetType: 'inline'
    script: |
      Add-VpnConnection -Name "greensqa@190.85.58.226" -ServerAddress "190.85.58.226" -PassThru
      $vpnname = "greensqa@190.85.58.226"
      $vpnusername = "vpn41"
      $vpnpassword = "9hg76j*23k71"
      $cmd = $env:WINDIR + "\System32\rasdial.exe"
      $expression = "$cmd ""$vpnname"" $vpnusername $vpnpassword"
      Invoke-Expression -Command $expression      
      ./ATH/aimaps/aimaps-cli/win-x64-no-driver/Gsqa.Tools.AiMaps.Console.exe src='$(Build.SourcesDirectory)/ATH/maps/Robot_Demo_ATH.aimj'
  displayName: 'Running robot - ATH '
  timeoutInMinutes: 10
