# The TIA - Team!

steps:

#- powershell: |
#         $destinationFolder = "$(Build.SourcesDirectory)/ATH/aimaps/aimaps-cli/win-x64-no-driver/selenium/"
#         if (!(Test-Path -path $destinationFolder)) {New-Item $destinationFolder -Type Directory}
#         Copy-Item 'C:/SeleniumWebDrivers/ChromeDriver/*' $destinationFolder -Force -Recurse
#  displayName: 'Install web drivers'
  
- task: PowerShell@2
  condition: eq(variables['Agent.OS'], 'Windows_NT')
  inputs:
    pws: true
    targetType: 'inline'
    script: |      
      $vpnname = "greensqa@190.85.58.226"
      $vpnusername = "vpn88"
      $vpnpassword = "4wt46N501VpN"
      $cmd = $env:WINDIR + "\System32\rasdial.exe"
      $expression = "$cmd ""$vpnname"" $vpnusername $vpnpassword"
      Invoke-Expression -Command $expression       
  displayName: 'Conect to VPN GreenSQA '
  timeoutInMinutes: 5
  
#- task: PowerShell@2
#  condition: eq(variables['Agent.OS'], 'Windows_NT')
#  inputs:
#    pws: true
#    targetType: 'inline'
#    script: |          
#      ./ATH/aimaps/aimaps-cli/win-x64-no-driver/Gsqa.Tools.AiMaps.Console.exe src='$(Build.SourcesDirectory)/ATH/maps/Robot_Demo_ATH.aimj'
#  displayName: 'Running robot - ATH '
#  timeoutInMinutes: 5  
