# The TIA - Team!

steps:

- powershell: |
    $destinationFolder = "$(Build.SourcesDirectory)/aimaps/aimaps-cli/win-x64/selenium/"
    if (!(Test-Path -path $destinationFolder)) {New-Item $destinationFolder -Type Directory}
    Copy-Item 'C:/SeleniumWebDrivers/ChromeDriver/*' $destinationFolder -Force -Recurse
  displayName: 'Install web drivers'
   
- task: PowerShell@2
  condition: eq(variables['Agent.OS'], 'Windows_NT')
  inputs:
    pws: true
    targetType: 'inline'
    script: |         
      ./aimaps/aimaps-cli/win-x64/Gsqa.Tools.AiMaps.Console.exe src='$(Build.SourcesDirectory)/Surtigas/maps/CBMDemoSurtigas.aiml'        
  displayName: 'Running robot - ShoppingCart '
  timeoutInMinutes: 15 
