# The TIA - Team!

steps:

- powershell: |
         $destinationFolder = "$(Build.SourcesDirectory)/GyF/aimaps/aimaps-cli/win-x64n/selenium/"
         if (!(Test-Path -path $destinationFolder)) {New-Item $destinationFolder -Type Directory}
         Copy-Item 'C:/SeleniumWebDrivers/ChromeDriver/*' $destinationFolder -Force -Recurse
  displayName: 'Install web drivers'
  
- task: PowerShell@2
  condition: eq(variables['Agent.OS'], 'Windows_NT')
  inputs:
    targetType: 'inline'
    script: |      
      ./GyF/aimaps/aimaps-cli/win-x64/Gsqa.Tools.AiMaps.Console.exe src='$(Build.SourcesDirectory)/GyF/maps/Robot_Demo_GyF.aimj'
  displayName: 'Running robot - Competidores '
  timeoutInMinutes: 10
