# The TIA - Team!

steps:

- powershell: |
    $destinationFolder = "$(Build.SourcesDirectory)/aimaps/aimaps-designer/selenium/"
    if (!(Test-Path -path $destinationFolder)) {New-Item $destinationFolder -Type Directory}
    Copy-Item 'C:/SeleniumWebDrivers/ChromeDriver/*' $destinationFolder -Force -Recurse
  displayName: 'Install web drivers'
   
- task: PowerShell@2
  condition: eq(variables['Agent.OS'], 'Windows_NT')
  inputs:
    pws: true
    targetType: 'inline'
    script: |          
      ./aimaps/aimaps-designer/AiMap.Console.exe src='$(Build.SourcesDirectory)/Icfes/maps/PLEXI.aiml' csv= '$(Build.SourcesDirectory)/Icfes/maps/PLEXI.csv'
  displayName: 'Running robot - Icfes '
  timeoutInMinutes: 60 
