# The TIA - Team!

steps:

#- powershell: |
#         $destinationFolder = "$(Build.SourcesDirectory)/ShoppingCart/aimaps/aimaps-cli/win-x64-no-driver/selenium/"
#         if (!(Test-Path -path $destinationFolder)) {New-Item $destinationFolder -Type Directory}
#         Copy-Item 'C:/SeleniumWebDrivers/ChromeDriver/*' $destinationFolder -Force -Recurse
#  displayName: 'Install web drivers'
  
- task: PowerShell@2
  condition: eq(variables['Agent.OS'], 'Windows_NT')
  inputs:
    pws: true
    targetType: 'inline'
    script: |
      Add-VpnConnection -Name "greensqa@190.85.58.226" -ServerAddress "190.85.58.226" -TunnelType "L2tp" -L2tpPsk '$(vpn-l2tpsk)' -Force -PassThru    
      $vpnname = "greensqa@190.85.58.226"
      $vpnusername = '$(vpn-user-name)'
      $vpnpassword = '$(vpn-password)'
      $cmd = $env:WINDIR + "\System32\rasdial.exe"
      $connect = "$cmd ""$vpnname"" $vpnusername $vpnpassword"
      Invoke-Expression -Command $connect                
  displayName: 'Connect to VPN'
  timeoutInMinutes: 5
  
- task: PowerShell@2
  condition: eq(variables['Agent.OS'], 'Windows_NT')
  inputs:
    pws: true
    targetType: 'inline'
    script: |          
      ./ATH/aimaps/aimaps-cli/win-x64/Gsqa.Tools.AiMaps.Console.exe src='$(Build.SourcesDirectory)/ShoppingCart/maps/Robot_Demo_ShoppingCart.aimj'
  displayName: 'Running robot - ShoppingCart '
  timeoutInMinutes: 20 

- task: PowerShell@2
  condition: eq(variables['Agent.OS'], 'Windows_NT')
  inputs:
    pws: true
    targetType: 'inline'
    script: |  
      $vpnname = "greensqa@190.85.58.226"
      $cmd = $env:WINDIR + "\System32\rasdial.exe"
      $disconnect = "$cmd ""$vpnname"" /disconnect"      
      Invoke-Expression -Command $disconnect
      Remove-VpnConnection -Name "greensqa@190.85.58.226" -Force      
  displayName: 'Disconnect to VPN'
  timeoutInMinutes: 5 
